name: Documentation

on:
  push:
    branches: [ ci/doc ]
 
  release:
    types: [created]

jobs:
  documentation:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements-ci.txt
        python -m pip install -e .
    - name: Sphinx Build
      run: make doc
    - name: Deploy to gh-pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        token: ${{ secrets.PAT }}
        branch: gh-pages
        folder: documentation/_build
        target-folder: docs
        clean: false

