name: Documentation

on:
  release:
    types: [created]

jobs:
  documentation:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements-ci.txt
        python -m pip install -e .
    - name: Sphinx Build
      run: make doc
    - name: Deploy to gh-pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        token: ${{ secrets.PAT }}
        branch: gh-pages
        folder: documentation/_build
        target-folder: docs
        clean: false

  documentation_index:
    name: Create documentation index
    needs: documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: gh-pages
    - name: Eumerate documentation releases
      run: |
        echo '[' > docs/index.json
        ls docs/ | grep -v latest | sort -r | sed -r 's|(.*)|"\1",|' >> docs/index.json
        echo ']' >> docs/index.json
    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with:
        author_name: pylover
        author_email: vahid.mardani@gmail.com
        message: 'Update: Documentation index'
        branch: gh-pages
        add: 'docs/index.json'
